### ISSUE TITLE
How to disabled the image assets plugin alone?

### ISSUE THREAD

**Issue by emptykid** [adobe-photoshop/generator-assets#424]
the image assets is binding to the photoshop host, and enabled by default.
while some times the plugin just crash down because of the **assert** function used in the code.
eg.

```
        assert.strictEqual(this.id, rawChange.id, "Document ID mismatch");
        assert.strictEqual(this.version, rawChange.version, "Version mismatch.");
```

when the plugin crash down, it breaks the **generator runtime** also, which makes my own generator plugin not working...
here is the exception log
```

Error trace: AssertionError: Document ID mismatch
    at Document._applyChange (C:\Program Files\Adobe\Adobe Photoshop CC 2017\Required\Plug-Ins\Generator\assets.generate\lib\dom\document.js:740:16)
    at DocumentManager._processNextChange (C:\Program Files\Adobe\Adobe Photoshop CC 2017\Required\Plug-Ins\Generator\assets.generate\lib\documentmanager.js:306:32)
    at DocumentManager.<anonymous> (C:\Program Files\Adobe\Adobe Photoshop CC 2017\Required\Plug-Ins\Generator\assets.generate\lib\documentmanager.js:256:18)
    at _fulfilled (C:\Program Files\Adobe\Adobe Photoshop CC 2017\Required\Generator-builtin\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Program Files\Adobe\Adobe Photoshop CC 2017\Required\Generator-builtin\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Program Files\Adobe\Adobe Photoshop CC 2017\Required\Generator-builtin\node_modules\q\q.js:749:13)
    at C:\Program Files\Adobe\Adobe Photoshop CC 2017\Required\Generator-builtin\node_modules\q\q.js:557:44
    at flush (C:\Program Files\Adobe\Adobe Photoshop CC 2017\Required\Generator-builtin\node_modules\q\q.js:108:17)
    at nextTickCallbackWith0Args (node.js:415:9)
    at process._tickDomainCallback (node.js:385:13)
```

Turn of the **Enable Generator** switch will shut down all generator plugins, that's not what i want.
So, is there some ways to disable the image assests plugin alone, 
Or make my own generator plugin in some other process?

thanks a lot.

xiaoqiang  from china.

**Comment by bialikover** [comment]
Any update on this? 

assets-generator is causing a problems in adobe cc 2019; bundled generator-assets: v2.9.8

This happens at some point when I send JSX to generator to execute:

```javascript
generator.evaluateJSXString()
```

```bash
[warning:generator-assets 00:11:51.579 document.js:848:38] Unhandled property in raw change: parentID 261
[warning:generator-assets 00:11:52.593 document.js:848:38] Unhandled property in raw change: parentID 195
[warning:generator-assets 00:14:19.947 document.js:848:38] Unhandled property in raw change: parentID 1163
[warning:generator-assets 00:14:20.758 document.js:848:38] Unhandled property in raw change: parentID 195
[warning:core 00:16:16.264 generator.js:133:30] Photoshop error { id: 206, body: 'Unknown JavaScript error' }
[error:app 00:16:16.266 app.js:350:25] Unknown JavaScript error
```
